.github/workflows/publish_docker.yml, Dockerfile, README.md
This will bring in a Dockerfile and hopefully Github Actions in order to automatically build and update the corresponding image.
=> Dockerfile

.github/workflows/publish_docker.yml, README.md
Thanks to @samlipworth who pointed at my improvable docker documentation.
=> update docker docs

Dockerfile
This updates edyeet and smoothxg. I also removed odgi itself as it is shipped within smoothxg anyhow.
=> update edyeet, smoothxg, remove odgi

pggb
Enables consensus graph output from smoothxg.
=> Consensus graph

Dockerfile
Hopefully fixes our current docker build.
=> trying to fix Dockerfile

.github/workflows/publish_docker.yml
This should also prevent problems like #30
=> also publish a snapshot of the docker image

.github/workflows/publish_docker.yml, Dockerfile, pggb
This should fix the problem encountered here #53
=> Fix docker edyeet/wfmash error

Dockerfile, pggb
support consensus specification string from smoothxg
=> Consensus spec

Dockerfile, README.md, pggb
This updates MultiQC so that it can handle our new file naming schema.
Also added documentation about how to read our 1D and 2D visualizations.
These issues came up in #51
=> fixed multiqc, added graph visualization explanations

Dockerfile
This attempts to fix the problem found in #62.
=> remove also `mcx16` flag for the compilation of the aligners

Dockerfile, pggb
=> Add the possibility to generate unique output directories

.github/workflows/build_and_test_docker.yml, Dockerfile, README.md, pggb
This merges tons of stuff that's been developed in the HPRC analysis. I think we can make v0.1 when this merges.
=> version 0.1 workup

.github/workflows/build_and_test_docker.yml, Dockerfile, pggb
Don't require consensus graph and MAF output. Make these optionally enabled with the -C and -F parameters.
Update to nice versions of smoothxg and wfmash.
=> Consensus less

Dockerfile
Trying to fix the issue in #62 and #95
=> remove mcx16 and march native also from WFA and wflambda

Dockerfile
This is (another) fix to tackle the issues like #62 and #95 more systematically.
=> remove mcx16 and march native also from smoothxg and its WFA dependency

Dockerfile
This updates `wfmash` to solve the problem in #62.
=> update wfmash with the last fix in the patching and the adaptive segment length

Dockerfile
Hopefully, this fixes https://github.com/pangenome/odgi/issues/282.
=> update smoothxg to 381fda4

.github/workflows/build_and_test_docker.yml, Dockerfile, README.md, pggb
Also update deps to release candidate branches.
=> expose smoothxg -O --poa-padding

pggb
This allows automatically displaying the current version of the script (and fixes #217).
```
pggb --version
pggb v0.4.0-10-g58b36e3
```
=> Add `--version` flag to display the version of `pggb`

Dockerfile, pggb
This improves both accuracy and runtime for the alignment of short/medium sequences (<= 20kbps).
=> update wfmash for better short/medium sequence alignment

.github/workflows/build_and_test_docker.yml, Dockerfile, pggb
This removes the explicit `smoothxg` loop from the `pggb` script.
=> Remove the `smoothxg` loop as it has been internalized in it

Dockerfile
Hi there,
I don't know if it's expected but I've not found the partition-before-pggb script so far.
So I propose this tiny pull request to add it to the container.
Best regards,
Thomas
=> add partition-before-pggb to docker container

scripts/mash2net.py, scripts/net2communities.py, scripts/paf2net.py
This helps for the future `nf-core/pangenome` here https://github.com/nf-core/pangenome/issues/70.
=> Executable scripts

Dockerfile
This fixes a bug introduced in https://github.com/pangenome/odgi/pull/507 and should fix also https://github.com/pangenome/pggb/issues/301.
=> update `smoothxg` with a working `odgi`

Dockerfile
The new `wfmash` strongly improves the runtime performance of both mapping and alignment (see https://github.com/waveygang/wfmash/pull/176).
=> Heuristic `wfmash`

Dockerfile
This is to resolve https://github.com/pangenome/pggb/issues/322.
=> add entire `scripts` folder in `bin`

partition-before-pggb, pggb
This PR follows the two commits sent directly to the master branch.
=> Update `wfmash` with the new `MashMap3`

partition-before-pggb, pggb
These changes are needed for the new `wfmash`.
=> update parameters and error messages

Dockerfile, pggb
=> Fix libwfa2cpp in the Docker image

Dockerfile, pggb
Updates wfmash to a new version which supports local inversion patching.
=> wfmash v0.16.0

README.md
=> updated link example pangenomes

Dockerfile, pggb
Working on having a "stable" PGGB in sync on GitHub/Docker/Singularity/Bioconda.
=> Revert wfmash 0.14.0, update seqwish, vcflib

partition-before-pggb, pggb
This fixes https://github.com/pangenome/pggb/issues/465
=> update PanSN regex to allow optional additional 3 or 4 pieces in naming
