Dockerfile

This brings in https://github.com/ekg/smoothxg/pull/8. Now `smoothxg` cuts blocks to prevent out of memory in POA.

bump smoothxg to 5308db3

---

pggb

We now log everything that is printed to stdout into a file for each process. However, `tee` is unhappy with `edyeet` and `wfmash`. For these tools I was not able to both print to console and a file at the same time, so I left it as it is.
Also, there is a possibility to run `odgi stats` for the `seqwish` and `smoothxg` GFAs. Just use `-S|--stats`.

write log files when possible, add an option for odgi stats

---

pggb

The current default settings can in some cases introduce "accordions" of smaller variants to represent large indels.
This sets a default that is slightly better, while still working on graphs that have relatively high divergence between the embedded genomes.
We should probably expose a set of default parameter settings for this that reflect the expected pairwise distance in the different POA settings.

Improve POA params

---

Dockerfile
pggb

Moreover, this increases a bit the number of merged blocks kept in memory to obtain consensus graphs with a bit bigger (and so less) nodes.

updated smoothxg with simplified cons graphs generation and more logging

---

Dockerfile

My last attempt to fix the `Illegal instruction` error of `edyeet` in `nf-core/pangenome` seemed successful. Trying the same for `wfmash` .
https://github.com/nf-core/pangenome/pull/44/checks?check_run_id=1989174704

more general wfmash build command

---

.github/workflows/build_and_test_docker.yml
Dockerfile
pggb

A frequent requirement is to compress the outputs, some of which (hello .maf) are highly compressible, redundant text collections. This enables the compression with the `-Z` flag.

optionally apply pigz to compressible products

---

Dockerfile
pggb

This sets up a new hybrid mapping mode where we:
1. map with default wfmash
2. map with wfmash -M (no-merge) and use the pggb "block-length" `-l` as the segment length `-s` input to wfmash (and set `-l` to 0)
The results are combined without filtering.
The logic is that the first phase encourages the alignment graph to form a star topology rooted in the longest sequences. This is the effect of the plane-sweep query filtering algorithm in mashmap2.
The second phase uses an updated feature in wfmash, which is a filtering mode for non-merged alignments that keeps the best `-n` mappings per query chunk. This will add links to our alignment graph between the most-closely related sequences.

Hybrid map

---

pggb

The consensus path merging appears to be introducing artifacts into the output graph. These then result in odd "block variants" in VCFs.
I also increase the default seqwish batch size to a more reasonable level (1M is tiny and only makes sense for extremely dense graphs).

disable consensus path merging

---

pggb

This is important on one of the systems I'm using. We depend on GNU time for the timing outputs, and we should find its actual disk path by `$(which time)`.

find time, don't assume it's /usr/bin/time

---

Dockerfile

This updates `wfmash` to close the #107 issue.

update wfmash with the fix in the CIGAR management in wflambda

---

Dockerfile

This updates `smoothxg`, hopefully solving https://github.com/pangenome/odgi/issues/282.

smoothxg: replacing dset64-gccAtomic.hpp with dset64.hpp

---

Dockerfile
pggb

using different POA target lengths, best performance seen when we use prime / non divisible lengths and scale up from the first to second smoothing

smooth twice, isn't that nice?

---

pggb

Called in this context, they are included in the sample names, breaking VCF generation.

don't confuse vg with quotes

---

Dockerfile

This updates the installation of `GFAfix`, which has been simplified after the fix of a critical bug in `rs-handlegraph`, and tries to reduce the permission noise for the executable (#128).

GFAffix fix in the Docker file

---

.github/workflows/build_and_test_docker.yml
Dockerfile
pggb

This includes updates to wfmash and smoothxg, as well as a change in semantics. The "block weight" parameter in smoothxg is now computed from `pggb -n` (which sets the number of multimappings in wfmash) or `pggb -H` (to specify the exact number of haplotypes) times the target length of the POA (given by `-G`) at the given smoothxg step.

Seeded abPOA

---

pggb

Always make the odgi viz renderings.
Don't specify `-v` anymore! The meaning is now reversed. This will probably catch a few users, but it can be rectified by re-running the same command line and adding `--resume` while removing the `-v` flag.

Auto viz always

---

pggb

This allows for a reduction in the size of the seqwish problem (in terms of disk/memory) using random sparsification of the matches in the input alignments. In practice, this helps for scaling up to large numbers of input genomes. If we use an expensive all-to-all alignment, we actually don't need to keep all the matches to infer the implied seqwish graph. Empirically we can allow for a very large amount of sparsification without affecting the graph. For instance, with only 7 yeast strains it's possible to remove 55% of the matches without affecting the seqwish graph (`pggb -f 0.45`).
For `n`-way alignment of `n` genomes, a rule of thumb seems to be to set the sparsification as a small multiple of `log(n)/n`. This draws on ideas from random graph theory which suggest that we should see a …

match sparsification

---

.github/workflows/build_and_test_docker.yml
README.md
docs/conf.py
docs/index.rst
docs/rst/optional_parameters.rst
docs/rst/quick_start.rst
docs/rst/smoothxg.rst
pggb

In `pggb`, `-n` is the number of haplotypes/genomes in the input dataset.
In `wfmash`, `-n` is the maximum number of mappings to consider for each homologous region identified in the input dataset. To avoid overlapping (relevant for small datasets), `wfmash -n` has to be set as `pggb -n` minus 1.
Furthermore, consensus graph generation has been disabled (due to #133 and #182 issues) and it will be for a while.

Handle `-n` differences between` pggb` and `wfmash`

---

pggb
scripts/net2communities.py

This allows greater control of the high-frequency kmers filtering. Repetitive genomes might require keeping more of such kmers for better mappings.

expose `-F, --mash-kmer-thres`

---

Dockerfile

It seems the most recent MultiQC v1.12 can't handle the given config file properly anymore. See https://github.com/ewels/MultiQC/issues/1649 and https://github.com/ewels/MultiQC/issues/1645.
This enforces v1.11 in the Dockerfile and subsequent docker images.

force MultiQC version 1.11 in Dockerfile

---

Dockerfile
pggb

This allows users to specify a directory for (big) temporary files other than the output directory.
It still needs a change in `seqwish`, `smoothxg`, and `odgi` to better manage the temporary directory there.

`--temp-dir` for specifying a directory for temporary files

---

Dockerfile
pggb

This lets us set a sparsification factor for the mappings in wfmash, which reduces alignment time. Mappings are sampled based on a hash of the mapping record. We take hash minimizing mapping records at the rate given by the sparsification factor.
It's also possible to set `pggb -x auto` to get an automatic sparsification setting based on the number of haplotypes (either `-n` or `-H`). This sets the wfmash sparsification to `10 * log(n) / n`, which appears to be a decent heuristic for panmictic populations. We might consider making this default, to reduce user issues that will become inevitable with high numbers of input genomes.

Sparsify mappings

---

Dockerfile

This allows users to fully work with the docker image, even for tasks like FASTA indexing (`samtools`), PanSN-spec renaming (`fastix`), community detection (`igraph` and `pycairo` Python libraries), and PAF plotting (`pafplot`).

CPANG22: add additional tools in the docker image

---

partition-before-pggb

This introduces a `partition-before-pggb` script to perform sequence partitioning and then generate a `pggb`'s command line for each community. These can be run separately in different cluster nodes.
The script is a big copy-paste of the `pggb`, removing a big chunk of it and adding the new partitioning logic. A smarter implementation would be nice, but practically, this current dirty solution works.
**Example**
```
partition-before-pggb -i data/HLA/DRB1-3123.fa.gz -p 95 -s 3000 -G 2000 -n 10 -t 2 -Z -V 'gi|568815561:#,gi|29124352:#:10000' -M -m -o drib1
[...]
Detected 3 communities.
[...]
pggb -i drib1/DRB1-3123.fa.gz.233010b.community.0.fa.gz \
-o drib1/DRB1-3123.fa.gz.233010b.community.0.fa.gz.out \
-p 3000 -l 25000 -p 95 -n 10 -K 19 -F 0.001 \
-k 19 -f 0 -B 10000000 \
-H 10 -j 0 -e 0 …
```

Adding the `partition-before-pggb` script to perform sequence partitioning before `pggb`

---

Dockerfile
partition-before-pggb
pggb

This helps reproducibility and debugging.
```
Starting pggb on 11-10-2022_09:59:47
Command: /home/guarracino/git/pggb/pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 10 -o drib1
PARAMETERS
general:
input-fasta:        data/HLA/DRB1-3123.fa.gz
output-dir:         drib1
temp-dir:           drib1
resume:             false
compress:           false
threads:            12
poa_threads:        12
wfmash:
version:            v0.10.0-6-g5791c12
segment-length:     3000
block-length:       25000
map-pct-id:         70
n-mappings:         10
no-splits:          false
sparse-map:         false
mash-kmer:          19
mash-kmer-thres:    0.001
exclude-delim:      false
no-merge-segments:  false
seqwish:
version:            v0.7.7-2-gf362f6f
min-match-len:      19
sparse-factor:      0 …
```

Emit tools' version in the LOG/YAML output

---

Dockerfile

Hi,
I've found that the scripts folder was missing to make partition-before-pggb work ;) 
I think it would be mandatory for pggb also.
Hope it'll help
best regards

Scripts folder added to /usr/local/bin/

---

Dockerfile
pggb

On average, this speeds up `smoothxg` by about 5X. In difficult cases, it goes much, much faster (see https://github.com/pangenome/smoothxg/pull/183).

update smoothxg to perform the POA on unique sequences

---

.github/workflows/build_and_test_docker.yml
Dockerfile

See https://github.com/pangenome/odgi/pull/482 and https://github.com/pangenome/smoothxg/pull/186.
Docker/Singularity images of PGGB display the wrong version of `odgi`. The `odgi` binary is correct, only the version it shows is wrong. In PGGB we use the `odgi` compiled with `smoothxg` and there the script to catch `odgi`'s version wrongly calls `smoothgx`'s git, not `odgi`'s.

Fix versioning

---

pggb

This adds support for metric suffixes by adding a function called "parse_numeric" that takes a numerical argument with a metric suffix and converts it to a plain number without the suffix.
This modifies the parameter parser to use this function for the `-s / --segment-length`, `-l / --block-length`, and `-B / --transclose-batch` parameters, replacing their previous behavior of accepting only plain numbers.
We add support for metric suffixes "k", "m", "g", and "t" (lowercase or uppercase) as multipliers for the numeric value. The purpose of this change is to allow users to input parameter values with metric suffixes for convenience, which seems to be expected given #289 and my own occasional error when setting in the `-s` parameter.

Support metric parameter suffixes

---

Dockerfile

SPOA and abPOA introduce links not supported by any path, leading to graphs with uncovered edges (see https://github.com/pangenome/pggb/issues/299). This PR avoids that and should fix https://github.com/pangenome/pggb/issues/299. Moreover, it adds a tiny optimization in case there are no blocks to flip.

update smoothxg to avoid uncovered edges

---

pggb

The help menu shows
```
-S, --stats                 generate statistics of the seqwish and smoothxg graph [default: off]
```
however, passing `--stats` returns the following error
```
pggb: unrecognized option '--stats'
```
The option that `getopt` is aware of is actuallt `--do-stats`. This PR changes it to reflect the help menu

make stats option consistent with help

---

pggb

symlinking `pggb` and asking for verison would report that there is no git repo. Here we read through the symlinked directory source, so we can still report pggb's version correctly.

handle version reporting if pggb is symlinked

---

partition-before-pggb
pggb

This is to avoid, by default, too complex graphs in repetitive regions.

A bit stronger filtering for mappings and matches

---

pggb

The arg parsing code (and associated variable) uses `--no-splits`, but the usage says the arg is called `--no-split`. 
thanks,
K

fix typo in usage regarding --no-splits

---

pggb

Allow
`pggb ... --resume -V prefix`
without computing previous steps again.

allow resuming for only variant calling

---

Dockerfile
pggb

The decomposed VCF file was not guaranteed to be sorted. Now it is.
Moreover, we go back to `vg deconstruct` 1.40.0 as newer versions still present issues with empty genotypes in the outputs.

`vg deconstruct` 1.40.0 (again) and sort decomposed VCF file

---

Dockerfile

Bumping bcftools to v1.19 fixes errors like
```
corrupted size vs. prev_size
.command.sh: line 28: 1163333 Aborted (core dumped) bcftools stats $vcf_decomposed > $vcf_decomposed.stats
```

multiqc 1.21, bcftools 1.19

---

partition-before-pggb
pggb

```shell
./pggb -i LPA.fa.gz -V 'chm13' -o out
[pggb] ERROR: the following tools are not installed or not in the PATH:
- wfmash
- seqwish
- smoothxg
- odgi
- gfaffix
- vcfbub
- vcfwave
- MultiQC
```
to avoid issues like in #388

check installed tools and report issues

---

README.md

 Resolving the `'Illegal option --'` error

---

partition-before-pggb
pggb

With low `-p`, the mapper was forced to examine lots of hits with little shared k-mers, increasing both runtime and memory. We avoid applying a too big filter with higher divergence.

Be smoother with the ANI filter in the mapping step

---

partition-before-pggb
pggb

Not a big deal with all tools, except `vg deconstruct` which strictly requires `haplotype_id`s to be numbers to emit correct VCF files.

PanSN requires a number as haplotype_id

---

partition-before-pggb
pggb

There is no record of what pggb version was used in the log files, which is probably useful information to check in case tool are out of sync.
On a side note, the `pggb --version` command only seems to work if you have the git version rather than a release tar. That gives an error like
```
fatal: Not a valid object name HEAD
```
Maybe there should be a release-pinned version as a variable to fall back on if the git version is not defined.

Add pggb version to its own log

---

partition-before-pggb
pggb

add a fall back version

---

pggb

Hopefully not missing something obvious, but you set the POA params in `pggb` via `-P` or `--poa-params`. This was passed on in the $poa_params_cmd variable to `smoothxg` as e.g. `poa_params_cmd="-P 1,19,39,3,81,1"`. However, `smoothxg` takes `-p` (lowercase) or `--poa-params`, and `-P` is instead the short arg for `--ref-paths`. As far as I can tell, consensus reference paths are ignored (commented out [here](https://github.com/pangenome/smoothxg/blob/e93c62356b33c2f6db727452328e09a33bfc82c6/src/main.cpp#L1071C13-L1071C23)), so maybe why this was not causing an error.
This might also explain what @baozg reported in #320, since `-P` is effectively a dead parameter and the default POA params get used anyway.

Correctly pass POA params to smoothxg

---

partition-before-pggb

Specifically, the flag was changed from a lowercase `-p` to an uppercase `-P`. The uppercase `-P` is what's described in the help text / docs and the lowercase `-p` conflicts with the percent identity for mapping/alignment flag.
Prior to this fix, none of the pggb commands generated by the `partition-before-pggb` script could be used because the POA score parameter arguments were being passed to the percent identity for mapping/alignment flag, causing a parse error.

[BUGFIX] Capitalized POA score parameters flag
